import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Main from "../components/Main/Main";
import About from "../components/About/About";
import CurrentProject from "../components/CurrentProject/CurrentProject";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Welcome to my portfolio !</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <Main />
          <About />
          <CurrentProject />
        </main>
      </div>
    </div>
  );
};

export default Home;
